### PR TITLE
Feature: Attach Photos Captured By Device Camera

### PR DESCRIPTION
**Pull request by Ismail-AD**
Issue #86 
Hello @aritra-tech ,

I hope you're doing well. I wanted to bring to your attention a new pull request I've submitted that introduces a valuable feature to the project.

**Pull Request Title:** Adding Camera Library for Image Attachment Feature

**Description:**

In this PR, I have added the CameraX library to  project, allowing users to capture and attach images to their notes.

**Video**
I have attached Video that demonstrate the new feature in action:

https://github.com/aritra-tech/Notify/assets/99780212/16b65b62-b6e9-4123-ac1e-8bfb24756502

**Request for Review:**

I request you to review this PR at your earliest convenience. If you have any feedback, suggestions, or questions, please feel free to let me know.

Thank you for your time and consideration. I look forward to your feedback.

### CODE REVIEW

**Comment by aritra-tech** [comment]
Hey, @Ismail-AD can you please fix the `ktlint` check?
Just run `./gradlew ktlintCheck --continue` in your terminal and check which lines are showing the error and fix it.

**Comment by Ismail-AD** [comment]
@aritra-tech bro I tried your mentioned command and tried almost every solution but nothing works EVEN WHEN APP IS LAUNCHING and WORKING very FINE.I have attached the ScreenShot can you help me to solve it out :  
error

**Comment by aritra-tech** [comment]
Okay let me have a look.

**Comment by aritra-tech** [comment]
I just checked your code and ran it the result I was expecting is not matched. I wanted that there would be a camera option that would enable the user to take images using their camera and when clicked it would be shown in the notes.
But what you have done is you are telling the user that after clicking the image from your camera you have to again go to the `Add Image` option and add that image which has been taken which is a wrong flow.

I hope you got the point @Ismail-AD what will you do now and what will be the flow?

**Comment by Ismail-AD** [comment]
I got you bro 😀

**Comment by aritra-tech** [comment]
Can you please fix the conflicts @Ismail-AD

**Comment by Ismail-AD** [comment]
okay i will check them

**Comment by Ismail-AD** [comment]
@aritra-tech i will suggest you to do test it and perform next action

**Comment by aritra-tech** [comment]
> @aritra-tech i will suggest you to do test it and perform next action

Yeah sure I will test it out and merge it soon if every thing went well.

**Comment by Ismail-AD** [comment]
@aritra-tech check is again pointing to problem which i told you yesteraday

**Comment by aritra-tech** [comment]
Required changes @Ismail-AD 

WhatsApp Image 2023-10-11 at 22 05 40_505aa790

- So in this image, as you can see, there are two notes the second one with title `Testing` in that note I have added images from my gallery and saved it and in the first note with title `Camera` I have added images from my camera but when I save those images in the card view images are same the images that I have clicked using my camera is getting replaced witht the images in the galley in the card view but when I click on the first note it shows me the correct images.
So look into this and do a thorough testing with all the possibilities you will get to know the bugs.
- When we are taking images from camera it shows us a toast that `Photo Attached Successfully`, you can do one thing after clicking any image show that toast and navigate back the user to the AddEditScreen.

I hope you got the point, take your take no need to hurry. 😊

**Comment by Ismail-AD** [comment]
@aritra-tech you can count me me dont worry..... you just find out how to fix that ktlint issue

**Comment by aritra-tech** [comment]
> @aritra-tech Bro WHEN i clicked images from camera as per your Image View Code i have to pass URI ok so i neeed to preserve my camera clicked image somewhere and that image is saving to gallery first after that i got the URI for that image as it is saved somewhere (in gallery) and that URI is then used to display image SECONDLY you open gallery to pick image you see that camera clicked image into GALLERY . AM I RIGHT OR WRONG (looking forward towards your clear statement for change If i am wrong and if right this is the way i need to genrate uri i am looking forward towards better suggestions as well)

Yeah got your point I was thinking differently.
But what about the same pictures showing up in the home screen

**Comment by Ismail-AD** [comment]
You mean user click images from camera and save a note and i next note user select image from gallery that is previously preserved image clicked to generate URI (so after saving second note both will have same images there is no exception in my point as per case it is OKAY, as image CLICKED through camera will definitely have to save somewhere) IF i am wrong again i am saying clear the change request statement BRO

**Comment by aritra-tech** [comment]
Actually, I was wrong.
The main problem is saving the images as URI can you do one thing can we change the type of saving image from URI to Bitmap?

**Comment by Ismail-AD** [comment]
> Actually, I was wrong. The main problem is saving the images as URI can you do one thing can we change the type of saving image from URI to Bitmap?

yup but first you have to manage your image side code rather display using uri display using IMAGE VIEW(bitmap) manage it then give me call i will refactor my side code is it okay ?

**Comment by Ismail-AD** [comment]
@aritra-tech as far as if we will try to change type which i will not suggest 2 things will happen we have to update Note Model to add list of bitmaps + Storing bitmaps as byte arrays INTO DATABASE can significantly increase the size of your database, leading to performance issues, increased storage requirements and Retrieving image data from a database can be slower  AND i will not suggest this rather we should go with previous approach (i am looking forward towards your response ).

**Comment by aritra-tech** [comment]
> @aritra-tech as far as if we will try to change type which i will not suggest 2 things will happen we have to update Note Model to add list of bitmaps + Storing bitmaps as byte arrays INTO DATABASE can significantly increase the size of your database, leading to performance issues, increased storage requirements and Retrieving image data from a database can be slower  AND i will not suggest this rather we should go with previous approach (i am looking forward towards your response ).

Okay your points are right. Let's then stick to URI only.
I will be merging your PR after some time.
Thanks for contributing @Ismail-AD

**Review by aritra-tech — APPROVED** [review]
LGTM 🚀
Thanks for contributing @Ismail-AD 🎉

**Pull request merged**
