### PR TITLE
Optimized code by combining screens

### LINKED ISSUE #82: Optimize the codebase
So now you can see that there are two `composable`  files for both **AddNote** & **EditNote** so it's better to combine these two files into one & also the `ViewModels ` are also different for every `composable` file so better to combine them into one.

### PR DESCRIPTION
**Pull request by bhoomi0104**
Fixed #82
Optimized code by combining AddNote and EditNote Screen and their ViewModels.

### CODE REVIEW

**Comment by aritra-tech** [comment]
There is some merge conflict coming up can you please fix it up @bhoomi0104

**Comment by bhoomi0104** [comment]
Resolve conflicts is disabled for me here.

**Comment by aritra-tech** [comment]
Use the command line to fix this.

**Comment by bhoomi0104** [comment]
It's fixed now

**Comment by aritra-tech** [comment]
Yeah, @bhoomi0104 I have seen that it is being fixed need to check the code once right now busy with some work.
Will be checking soon.

**Review by aritra-tech — APPROVED** [review]
LGTM 👍

**Pull request merged**
