### PR TITLE
feat(checklist): implemented the checklist

### LINKED ISSUE #127: Feat : TODO list
There will be option to add todo list (checkboxes) in the notes.

### PR DESCRIPTION
**Pull request by logickoder**
closes #127 

https://github.com/aritra-tech/Notify/assets/42023982/631b6e8b-0f07-4a80-bc1b-25cce45d75a1

### CODE REVIEW

**Comment by logickoder** [comment]
@aritra-tech please review

**Comment by aritra-tech** [comment]
So some changes
- Right now you are using `Show Checklist` to show the checkboxes, but we need to remove it and place it in the bottom sheet along with `Drawing`. I hope you got it.
- On clicking on the `Show Checklist` it opens up a  bottom sheet where are can add our checkboxes but I want to show the checkboxes along with the notes, check Google Keep Notes once you will be very clear what I wanted.

**Comment by logickoder** [comment]
@aritra-tech please review

https://github.com/aritra-tech/Notify/assets/42023982/ea539ee9-b088-48fd-9879-587390b45863

**Comment by aritra-tech** [comment]
https://github.com/aritra-tech/Notify/assets/80090908/ee1bf1e7-f249-45fd-9ed7-28399998a40d

After saving a note with todos when I try to edit that note and delete one of the todos that I've written and update the note when I again go to that note the todo that I have deleted is still there.
Sometimes the card works abnormally if I click on some other card it opens to some other card.
Can you please look into it

**Comment by logickoder** [comment]
@aritra-tech please review

**Review by aritra-tech — APPROVED** [review]
LGTM ✔

**Pull request merged**
