### PR TITLE
Implemented auto-update on new changes to note

### PR DESCRIPTION
**Pull request by ibrahim-5**
Note app now saves notes when user navigates back using the edit bar and the native phone back button.
These updates only occur when there have been changes to the note.

Fixes: #24

### CODE REVIEW

**Comment by aritra-tech** [comment]
Nice work @ibrahim-5 but you only added the auto-save note when the user updates it, but can we also do it same when the user add/save the note.

**Comment by ibrahim-5** [comment]
> During the Add Note Screen, the autosave will only be applicable when the user presses phone back button. I hope this is clear to you.

Just to clarify, the note won't be saved if the user presses the back button on the bar? I think that would make sense

**Comment by aritra-tech** [comment]
> > During the Add Note Screen, the autosave will only be applicable when the user presses phone back button. I hope this is clear to you.
> 
> Just to clarify, the note won't be saved if the user presses the back button on the bar? I think that would make sense

Yeah right it will be saved if the user clicks on the tick button on the top-app bar and when the user press the phone's back back. But it will not save the note when the user clicks on the back button that is present on the top-app bar.

**Comment by aritra-tech** [comment]
LGTM 👍

**Pull request merged**
