### PR TITLE
Feat: multi-selection-deletion-items

### LINKED ISSUE #99: Add Feature : Multi-selection for deleting notes
Currently, users must open a note to delete it. This can be complex, especially if users have a large number of notes. A swipe to delete feature would allow users to delete notes from the home screen with a single gesture, making it much easier and faster to manage their notes.

### PR DESCRIPTION
**Pull request by bhoomi0104**
Fixed #99 

Using this feature, the user can select multiple notes and delete them. When user delete the note items, they can undo the process as well.

### CODE REVIEW

**Comment by aritra-tech** [comment]
Please fix the ktlintCheck.
In your terminal run this command ```./gradlew ktlintCheck --continue```, it will give you the lines where the code style is not appropriate.

**Comment by bhoomi0104** [comment]
It's done!

**Comment by aritra-tech** [comment]
In the dark-mode the card is not visible it's color is white
WhatsApp Image 2023-10-06 at 23 32 50_34988eaa

**Comment by bhoomi0104** [comment]
It's fixed

Screenshot_20231007-001016
Screenshot_20231007-001020

**Review by aritra-tech — APPROVED** [review]
LGTM 🙌
Nice work @bhoomi0104 🚀

**Pull request merged**
