### PR TITLE
Single tap top

### PR DESCRIPTION
**Pull request by githubashutoshsoni**
added scroll to top when notes item is clicked.

### CODE REVIEW

**Comment by githubashutoshsoni** [comment]
@aritra-tech merge conflict is resolved now.

**Comment by githubashutoshsoni** [comment]
Can you please accept this merge reqeuest?

**Comment by githubashutoshsoni** [comment]
@aritra-tech You mentioned you added to the PR. But I don't see it anywhere. Can you please share again over here?

**Comment by aritra-tech** [comment]
> @aritra-tech You mentioned you added to the PR. But I don't see it anywhere. Can you please share again over here?

I have added a code review not the PR.

**Comment by githubashutoshsoni** [comment]
Yes, I did not receive this notification anywhere in the github. I got the code changes so I will implement them. If possible can you share the link for review here so I can get access to it?

**Comment by githubashutoshsoni** [comment]
Kindly add reviews that needs to be added over here. I've implemented the changes now @aritra-tech

**Review by aritra-tech — APPROVED** [review]
LGTM 👍

**Pull request merged**
