### PR TITLE
feature: Add sorting options for notes.

### PR DESCRIPTION
**Pull request by V9vek**
Added the notes sorting feature, resolving the issue https://github.com/aritra-tech/Notify/issues/118

It includes sorting notes based on:

Date (Oldest | Newest)
Title (A-Z | Z-A)
You can see the implementation in the attached video.
And one more thing, the Gradle Lint is showing error out of nowhere every time

If this looks good to you, please merge the request 😊
or if you need some changes, please do ping me.

https://github.com/aritra-tech/Notify/assets/40730402/ea246125-6585-4270-b048-1521437f5fc3

### CODE REVIEW

**Comment by aritra-tech** [comment]
Hey @V9vek can you please fix the `ktlint` check.
Just run `./gradlew ktlintCheck --continue` in your terminal and check which lines are showing the error.

**Comment by V9vek** [comment]
> Hey @V9vek can you please fix the `ktlint` check. Just run `./gradlew ktlintCheck --continue` in your terminal and check which lines are showing the error.

okay sure

**Comment by V9vek** [comment]
@aritra-tech can you check now?

**Review by aritra-tech — APPROVED** [review]
LGTM 🙌
Nice work @V9vek

**Pull request merged**
