### PR TITLE
Implement backup and restore with csv

### LINKED ISSUE #45: Fix the data backup/restore feature
Change the data backup & restore feature and implement a feature that allows the user to backup & restore their data in the form of CSV.

### LINKED ISSUE #67: The app crashes when trying to backup and there is a note with an image
I have created the first note with a simple text, then created a second note with text and an image of type **JPG**, when I tried to make a backup of the database the app crashes showing the following error in logcat

```
FATAL EXCEPTION: main
Process: com.aritra.notify, PID: 1841
java.lang.RuntimeException: Could not copy bitmap to parcel blob.
	at android.graphics.Bitmap.nativeWriteToParcel(Native Method)
	at android.graphics.Bitmap.writeToParcel(Bitmap.java:2180)
	at android.os.Parcel.writeParcelable(Parcel.java:2538)
	at android.os.Parcel.writeValue(Parcel.java:2439)
	at android.os.Parcel.writeValue(Parcel.java:2316)
	at androidx.compose.runtime.ParcelableSnapshotMutableState.writeToParcel(ParcelableSnapshotMutableState.kt:30)
	at android.os.Parcel.writeParcelable(Parcel.java:2538)
	at android.os.Parcel.writeValue(Parcel.java:2439)
	at android.os.Parcel.writeValue(Parcel.java:2316)
	at android.os.Parcel.writeList(Parcel.java:1382)
	at android.os.Parcel.writeValue(Parcel.java:2460)
	at android.os.Parcel.writeValue(Parcel.java:2316)
	at android.os.Parcel.writeMapInternal(Parcel.java:1233)
	at android.os.Parcel.writeMap(Parcel.java:1215)
	at android.os.Parcel.writeValue(Parcel.java:2430)
	at android.os.Parcel.writeValue(Parcel.java:2316)
	at android.os.Parcel.writeMapInternal(Parcel.java:1233)
	at android.os.Parcel.writeMap(Parcel.java:1215)
	at android.os.Parcel.writeValue(Parcel.java:2430)
	at android.os.Parcel.writeValue(Parcel.java:2316)
	at android.os.Parcel.writeList(Parcel.java:1382)
	at android.os.Parcel.writeValue(Parcel.java:2460)
	at android.os.Parcel.writeValue(Parcel.java:2316)
	at android.os.Parcel.writeMapInternal(Parcel.java:1233)
	at android.os.Parcel.writeMap(Parcel.java:1215)
	at android.os.Parcel.writeValue(Parcel.java:2430)
	at android.os.Parcel.writeValue(Parcel.java:2316)
	at android.os.Parcel.writeMapInternal(Parcel.java:1233)
	at android.os.Parcel.writeMap(Parcel.java:1215)
	at android.os.Parcel.writeValue(Parcel.java:2430)
	at android.os.Parcel.writeValue(Parcel.java:2316)
	at android.os.Parcel.writeList(Parcel.java:1382)
	at android.os.Parcel.writeValue(Parcel.java:2460)
	at android.os.Parcel.writeValue(Parcel.java:2316)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1265)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
	at android.os.Bundle.writeToParcel(Bundle.java:1362)
	at android.os.Parcel.writeBundle(Parcel.java:1334)
	at android.os.Parcel.writeValue(Parcel.java:2433)
	at android.os.Parcel.writeValue(Parcel.java:2323)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1265)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
	at android.os.Bundle.writeToParcel(Bundle.java:1362)
	at android.os.Parcel.writeBundle(Parcel.java:1334)
	at android.os.Parcel.writeValue(Parcel.java:2433)
	at android.os.Parcel.writeValue(Parcel.java:2323)
	at android.os.Parcel.writeTypedObject(Parcel.java:2157)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1257)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:99)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8296)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

```

### PR DESCRIPTION
**Pull request by logickoder**
closes #67 

closes #45 

image

image

### CODE REVIEW

**Comment by aritra-tech** [comment]
Can you send a video, actually I tried to run your branch but as the pictures shows it's not working like that.

**Comment by logickoder** [comment]
Ohh, sorry for the misleading image, this is the files by Google app, when I tried opening the zip file

**Comment by logickoder** [comment]
Clicking on backup askes you for the file name, and it creates the archive there. Importing reads the specified archive and overites the database with the information

**Comment by aritra-tech** [comment]
> Clicking on backup askes you for the file name, and it creates the archive there. Importing reads the specified archive and overites the database with the information

Can you please share a video regarding the changes.

**Review by aritra-tech — APPROVED** [review]
LGTM 👍
Nice work @logickoder

**Comment by aritra-tech** [comment]
Hey @logickoder can you check the issue number #73
After merging this PR that bug is coming up.
Please have a look once.

**Comment by logickoder** [comment]
Ahh, would take a look at it once I'm chanced

**Comment by aritra-tech** [comment]
> Ahh, would take a look at it once I'm chanced

So, I am assigning that issue to you.

**Comment by aritra-tech** [comment]
Hey @logickoder any update?
Actually I was thinking of releasing it with the latest changes so if you can check the bug once.
Otherwise for this release I have to revert back the changes and fix it up and release on the next update.

**Comment by logickoder** [comment]
Ahh, I've been really busy at work, I'll have a look at it today and make a fix

**Comment by aritra-tech** [comment]
Okay take your time I will make a release on Sunday.

**Pull request merged**
