### PR TITLE
Create a reminder section

### PR DESCRIPTION
**Pull request by salmanA169**
https://github.com/aritra-tech/Notify/assets/40442174/6ea2ff91-651c-47be-8184-1b1e05565fdd

issue #84

### CODE REVIEW

**Comment by aritra-tech** [comment]
If I save the Note using only the title and description and not giving any reminder then it's getting saved but when I am trying to delete that Note it's crashing.
Can you please check this out @salmanA169.

**Comment by salmanA169** [comment]
No 
this issue from drawing canvas version it uses 
compose-ui = "androidx.compose.ui:ui:1.6.0-alpha08"

you must replace this with this stable version 
compose-ui = "androidx.compose.ui:ui:1.5.4"

this issue from alpha version bug for lazy column internally

**Comment by aritra-tech** [comment]
Can you please change it out?

**Comment by salmanA169** [comment]
Yes I can
Buht there is new issue
When downgrade version on drawing screen has error because on alpha Verizon there is new util extention fun for drawing
I am trying to solve this
I am not good at drawing views also but I will try

**Comment by salmanA169** [comment]
check it again now you can move note to trash without throw

**Comment by aritra-tech** [comment]
WhatsApp Image 2023-11-01 at 11 03 05_86641c7c
WhatsApp Image 2023-11-01 at 11 03 05_f589dd46

In the list view the reminder is showing up in the card but when I change to grid view the reminder part is not there. Can you please fix it up? Apart from that it's working fine.
Good work 🙌

**Comment by salmanA169** [comment]
Oh I forget it
OK I will do that

**Comment by salmanA169** [comment]
Screenshot_20231101_222150

**Pull request merged**
