### PR TITLE
Feature: Implemented shortcuts

### PR DESCRIPTION
**Pull request by tuuhin**
Link to the issue #446 

### Description
 
Shortcuts help in quickly access parts of an app 
This is really helpful in notes app as user can directly move to create note or other contents without the normal workflow before reaching the required destinations

### Added two shortcuts
-  One to create note 
- Open the trash bin (this doesn't seems required one )

Please let me know if you want any changes.

### CODE REVIEW

**Comment by aritra-tech** [comment]
For now please remove the shortcut to `open trash bin`
It's of no use.
@tuuhin

**Comment by tuuhin** [comment]
Yeah I just wanted to check if the deep links are working...
Oke I will remove it tomorrow 
So for the meantime only shortcut will be  create a note ?

**Comment by aritra-tech** [comment]
> Yeah I just wanted to check if the deep links are working... Oke I will remove it tomorrow So for the meantime only shortcut will be create a note ?

yeah just for creating the note

**Review by aritra-tech — APPROVED** [review]
LGTM 👍🏻

**Comment by tuuhin** [comment]
Happy to help 😅

**Pull request merged**
