### PR TITLE
Adding-support-for-pinning-new-notes

### PR DESCRIPTION
**Pull request by Kayvee08**
https://github.com/aritra-tech/Notify/issues/186

### CODE REVIEW

**Comment by aritra-tech** [comment]
Can you please fix the merge conflict and please give the branch name related to the name of the `issue` it gets hard for me to test which branch to check.
I hope you understand @Kayvee08

**Comment by Kayvee08** [comment]
@aritra-tech I think I'will have to raise new PR,
Base bran
ch cannot be updated

**Comment by aritra-tech** [comment]
> @aritra-tech I think I'will have to raise new PR, Base branch cannot be updated

For at this point no need to create a new PR I will check the code through browser only. Just do two things
- Send me a video of the working
- Fix the merge conflict

**Comment by Kayvee08** [comment]
@aritra-tech sharing

**Comment by aritra-tech** [comment]
Please fix the `ktlint` check

**Comment by aritra-tech** [comment]
Any update @Kayvee08?

**Comment by Kayvee08** [comment]
@aritra-tech was stuck in some office work, will update soon

**Comment by aritra-tech** [comment]
> @aritra-tech was stuck in some office work, will update soon

Okay okay no issue.

**Comment by aritra-tech** [comment]
Hey @Kayvee08 any update?
Actually, I was thinking of making a release today so if you can make the required changes then I can also add your changes to this latest release.
Thank you

**Comment by aritra-tech** [comment]
Sorry @Kayvee08 I am closing this PR.
Thanks for contributing.

**Pull request closed without merging**
